[package]
name = "tikv-client"
version = "0.0.0"
keywords = ["TiKV", "KV", "distributed-systems"]
license = "Apache-2.0"
authors = ["The TiKV Project Authors"]
repository = "https://github.com/tikv/client-rust"
description = "The rust language implementation of TiKV client."
edition = "2018"

[features]
default = []
# Enable integration tests with a running TiKV and PD instance.
# Use $PD_ADDRS, comma separated, to set the addresses the tests use. 
integration-tests = []

[lib]
name = "tikv_client"

[dependencies]
derive-new = "0.5"
failure = "0.1"
futures = { version = "0.3.1", features = ["compat", "async-await", "thread-pool"] }
grpcio = { version = "0.5.0-alpha", features = [ "secure", "prost-codec" ], default-features = false }
kvproto = { git = "https://github.com/yuchenECNU/kvproto.git", rev = "2362c0973efc6c5d6ad984d6b55cf0f01fc5b9d3", features = [ "prost-codec" ], default-features = false }
lazy_static = "1"
log = "0.3.9"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
futures-timer = "2.0"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["push", "process"]

[dev-dependencies]
clap = "2.32"
tempdir = "0.3"
runtime = { version = "0.3.0-alpha.8", default-features = false }
runtime-tokio = "0.3.0-alpha.6"
proptest = "0.9"
proptest-derive = "0.1.0"
fail = { version = "0.3", features = [ "failpoints" ] }
